In [197]:
# Chapter 4: Numpy 
import numpy as np

# 2D arrays
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
arr2d[2, 1]
arr2d[2, 1:]
arr2d[:, :2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2],
       [4, 5],
       [7, 8]])

In [3]:
# 3D arrays
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [25]:
print(arr3d[0])
print(arr3d[0, 0])
print(arr3d[0, 0, 0])
print(arr3d[:, :, 0])
print(arr3d[:2, 1:])

[[1 2 3]
 [4 5 6]]
[1 2 3]
1
[[ 1  4]
 [ 7 10]]
[[[ 4  5  6]]

 [[10 11 12]]]


In [201]:
# Populating and reshaping an array
arr = np.arange(32).reshape((8, 4))

In [202]:
# Retrieving elements
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [37]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [38]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [203]:
# Select the full square region

arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])] 

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [41]:
# Dot multiplication and transpose
np.dot(arr.T, arr)

array([[2240, 2352, 2464, 2576],
       [2352, 2472, 2592, 2712],
       [2464, 2592, 2720, 2848],
       [2576, 2712, 2848, 2984]])

In [44]:
# Meshgrid creates a 2D matrix from two 1D arrays
points = np.arange(-5, 5, 0.01)
xs, ys = np.meshgrid(points, points)
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [204]:
# numpy.where function is a vectorized version of the ternary expression
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
# result = [(x if c else y)
#         for x, y, c in zip(xarr, yarr, cond)]
result = np.where(cond, xarr, yarr)
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [51]:
# Storing arrays
np.save('some_array', arr)
np.load('some_array.npy')
# np.savez('array_archive.npz', a=arr, b=arr) for multiples

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [53]:
# Loading csv
# arr = np.loadtxt('array_ex.txt', delimiter=',')
# np.savetxt

In [205]:
# Series
from pandas import Series, DataFrame
obj = Series([4, 7, -5, 3])
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)

In [206]:
# Data frame
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
frame
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                   index=['one', 'two', 'three', 'four', 'five'])
frame2.loc['three']
frame2.iloc[0]

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object

In [74]:
# Retrieve element by Index
frame2.iloc[:, 0]

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [85]:
frame2.get_value

<bound method DataFrame.get_value of        year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN>

In [70]:
# Reindexing (since be cannot directly mutate the index)
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [89]:
# Apply
frame = DataFrame(np.random.randn(4, 3), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
f = lambda x: x.max() - x.min()
frame.apply(f)

b    2.439539
d    4.406603
e    1.274196
dtype: float64

In [90]:
# Apply using columns
frame.apply(f, axis=1)

Utah      1.574675
Ohio      2.109265
Texas     4.266676
Oregon    1.802439
dtype: float64

In [92]:
# Applymap for element-wise changes
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah    -1.13  -0.83   0.45
Ohio     0.74   1.45  -0.66
Texas    1.31  -2.95   0.62
Oregon  -0.49   1.31  -0.24

In [103]:
# Correlation and Covariance
# pandas.io.data is deprecated
import pandas_datareader as pdr
all_data = {}
for ticker in ['AAPL', 'IBM']:
    all_data[ticker] = pdr.get_data_yahoo(ticker, '1/1/2000', '1/1/2010')
price = DataFrame({tic: data['Adj Close']
    for tic, data in all_data.items()})
volume = DataFrame({tic: data['Volume']
    for tic, data in all_data.items()})

returns = price.pct_change()

In [108]:
returns.tail()

AAPL       IBM
Date                          
2009-12-24  0.034340  0.004384
2009-12-28  0.012294  0.013326
2009-12-29 -0.011861 -0.003477
2009-12-30  0.012147  0.005461
2009-12-31 -0.004300 -0.012597

In [109]:
returns.AAPL.corr(returns.IBM)

0.41001161890475174

In [116]:
# Handling missing data

from numpy import nan as NA
df = DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
_ = df.fillna(0, inplace=True)
df.fillna({1: 0.5, 3: -1}) # diff fill value for columns
data = Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [117]:
# Hierarchical indexing
data = Series(np.random.randn(10),
              index=[['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'],
                     [1, 2, 3, 1, 2, 3, 1, 2, 2, 3]])

In [118]:
data

a  1   -1.117786
   2   -0.922185
   3   -0.074275
b  1   -1.171213
   2    1.137231
   3   -0.826753
c  1    0.361122
   2   -0.816997
d  2    2.493534
   3   -0.467652
dtype: float64

In [120]:
data['b':'c']

b  1   -1.171213
   2    1.137231
   3   -0.826753
c  1    0.361122
   2   -0.816997
dtype: float64

In [122]:
data.loc[['b','d']]

b  1   -1.171213
   2    1.137231
   3   -0.826753
d  2    2.493534
   3   -0.467652
dtype: float64

In [140]:
# Chapter 6 Data loading and storage
# JSON
obj = """ 
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 25, "pet": "Zuko"},
              {"name": "Katie", "age": 33, "pet": "Cisco"}]
}
"""
import json
result = json.loads(obj)

In [142]:
siblings = DataFrame(result['siblings'], columns=['name', 'age'])
siblings

name  age
0  Scott   25
1  Katie   33

In [144]:
# Web scraping
from lxml.html import parse
# from urllib2 import urlopen - split into request and error modules
from urllib.request import urlopen

parsed = parse(urlopen('http://finance.yahoo.com/q/op?s=AAPL+Options'))
doc = parsed.getroot()
urls = [link.get('href') for link in doc.findall('.//a')]

In [171]:
urls[-10:]

['https://smallbusiness.yahoo.com',
 'https://help.yahoo.com/kb/index?page=content&y=PROD_FIN_DESK&locale=en_US&id=SLN2310',
 'https://help.yahoo.com/kb/index?page=content&y=PROD_FIN_DESK&locale=en_US',
 'https://yahoo.uservoice.com/forums/382977',
 'http://info.yahoo.com/privacy/us/yahoo/',
 'http://info.yahoo.com/relevantads/',
 'http://info.yahoo.com/legal/us/yahoo/utos/utos-173.html',
 'https://twitter.com/YahooFinance',
 'https://facebook.com/yahoofinance',
 'http://yahoofinance.tumblr.com']

In [152]:
tables = doc.findall('.//table')
calls = tables[1]
puts = tables[2]

In [161]:
rows = calls.findall('.//tr')
def _unpack(row, kind='td'):
    elements = row.findall('.//%s' % kind)
    return [val.text_content() for val in elements]

In [162]:
_unpack(rows[0], kind='th')

['Contract Name',
 'Last Trade Date',
 'Strike',
 'Last Price',
 'Bid',
 'Ask',
 'Change',
 '% Change',
 'Volume',
 'Open Interest',
 'Implied Volatility']

In [164]:
_unpack(rows[1], kind='td')

['AAPL170908C00120000',
 '2017-09-01 10:32AM EDT',
 '120.00',
 '44.12',
 '43.70',
 '44.35',
 '+6.18',
 '+16.29%',
 '50',
 '0',
 '132.03%']

In [172]:
# Convert the data into a data frame
from pandas.io.parsers import TextParser

def parse_options_data(table):
    rows = table.findall('.//tr')
    header = _unpack(rows[0], kind='th')
    data = [_unpack(r) for r in rows[1:]]
    return TextParser(data, names=header).get_chunk()

In [176]:
call_data = parse_options_data(puts)
call_data.head()

Contract Name         Last Trade Date  Strike  Last Price  Bid   Ask  \
0  AAPL170908P00120000   2017-08-24 3:05PM EDT   120.0        0.01  0.0  0.03   
1  AAPL170908P00125000   2017-08-30 3:45PM EDT   125.0        0.01  0.0  0.01   
2  AAPL170908P00130000   2017-08-30 3:50PM EDT   130.0        0.01  0.0  0.02   
3  AAPL170908P00135000   2017-08-31 3:59PM EDT   135.0        0.01  0.0  0.01   
4  AAPL170908P00137000  2017-09-01 10:48AM EDT   137.0        0.01  0.0  0.01   

   Change % Change Volume Open Interest Implied Volatility  
0     0.0        -      6            80             89.06%  
1     0.0        -    150           307             70.31%  
2     0.0        -     34           201             65.63%  
3     0.0        -    206           246             51.56%  
4     0.0        -    202           567             51.56%

In [180]:
# XML
from lxml import objectify
path = 'Performance_MNR.xml'
parsed = objectify.parse(open(path))
root = parsed.getroot()

In [182]:
data = []
skip_fields = ['PARENT_SEQ', 'INDICATOR_SEQ', 'DESIRED_CHANGE', 'DECIMAL_PLACES']

In [195]:
for element in root:
    element_data ={}
    for child in element.getchildren():
        if child.tag in skip_fields:
            continue
        element_data[child.tag] = child.pyval
    data.append(element_data)
perf = DataFrame(data)
perf

AGENCY_NAME            CATEGORY  \
0  Metro-North Railroad  Service Indicators   
1                   NaN                 NaN   

                                         DESCRIPTION FREQUENCY  \
0  Percent of the time that escalators are operat...         M   
1                                                NaN       NaN   

           INDICATOR_NAME INDICATOR_UNIT MONTHLY_ACTUAL  MONTHLY_TARGET  \
0  Escalator Availability              %                           97.0   
1                     NaN            NaN            NaN             NaN   

   PERIOD_MONTH  PERIOD_YEAR YTD_ACTUAL  YTD_TARGET  
0          12.0       2011.0                   97.0  
1           NaN          NaN        NaN         NaN

In [194]:
# Handling XML tags with metadata
# from StringIO import StringIO  - replaced by io.StringIO
from io import StringIO
tag = '<a href="http://www.google.com">Google</a>'
root = objectify.parse(StringIO(tag)).getroot()
print(root.get('href'))
print(root.text)

http://www.google.com
Google


In [211]:
# Binary Data Formats
# pickle as a short-term storage format
frame = pd.read_csv('example.csv')
# frame.save('example_pickle') - 'DataFrame' object has no attribute 'save'
frame.to_pickle('example_pickle')
pd.read_pickle('example_pickle')

Empty DataFrame
Columns: [1, 2, 3]
Index: []

In [220]:
# HDF5
# hierarchical data format for large data
# best suited for write-once, read-many datasets
import h5py
file = h5py.File('mydata2.h5','w')
dataset = file.create_dataset("dset",(4, 6), h5py.h5t.STD_I32BE)

In [221]:
print("Dataset dataspace is", dataset.shape)
file.close

Dataset dataspace is (4, 6)


<bound method File.close of <HDF5 file "mydata2.h5" (mode r+)>>

In [222]:
store = pd.HDFStore('mydata2.h5')
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata2.h5
Empty

In [ ]:
# Excel files
# xls_file = pd.ExcelFile('data.xls')
# table = xls_file.parse('Sheet1')

In [226]:
# Web APIs
# Search for a keyword in twitter
import requests
import json

# Outdated query string and returns <Response [410]>
# url = 'http://search.twitter.com/search.json?q=python%20pandas'
# refer to https://dev.twitter.com/rest/public/search
url = "https://api.twitter.com/1.1/search/tweets.json?q=python%20pandas"
response = requests.get(url)
data = json.loads(response.text)

# Twitter API requires api key to authenticate
# {'errors': [{'code': 215, 'message': 'Bad Authentication data.'}]}

In [231]:
# Trying a different API for this exercise
parameters = {"lat": 42.36, "lon": -71.06}
url = "http://api.open-notify.org/iss-pass.json"
response = requests.get(url, params=parameters)
data = json.loads(response.text)

In [232]:
data

{'message': 'success',
 'request': {'altitude': 100,
  'datetime': 1504476551,
  'latitude': 42.36,
  'longitude': -71.06,
  'passes': 5},
 'response': [{'duration': 575, 'risetime': 1504511246},
  {'duration': 643, 'risetime': 1504516984},
  {'duration': 593, 'risetime': 1504522828},
  {'duration': 586, 'risetime': 1504528673},
  {'duration': 637, 'risetime': 1504534473}]}

In [236]:
fields = ['duration', 'risetime']
df = DataFrame(data['response'], columns=fields)
df

duration    risetime
0       575  1504511246
1       643  1504516984
2       593  1504522828
3       586  1504528673
4       637  1504534473

In [238]:
# Interacting with databases

# SQLite
import sqlite3

query = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
 c REAL, d INTEGER);
"""

con = sqlite3.connect(':memory:')
con.execute(query)
con.commit()

In [239]:
# Insert data
data = [('Atlanta', 'Georgia', 1.25, 6), ('Tallahassee', 'Florida', 2.6, 3), ('Sacramento', 'California', 1.7, 5)]
statement = "INSERT INTO test VALUES(?, ?, ?, ?)"

con.executemany(statement, data)
con.commit()

In [240]:
cursor = con.execute('select * from test')
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [246]:
# Zip returns an iterable in Python 3 instead of a list
# DataFrame(rows, columns=list(zip(*cursor.description))[0])
DataFrame(rows, columns=next(zip(*cursor.description)))

a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [248]:
# Alternative: use read_sql (read_frame is deprecated)
import pandas.io.sql as sql

sql.read_sql('select * from test', con)

a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [253]:
# MongoDB
# Start a local MongoDB instance 
# mongod --config /usr/local/etc/mongod.conf

# Connect to it using pymongo
# import pymongo
# con = pymongo.Connection('localhost', port=27017)

# Connection is deprecated, use MongoClient instead
from pymongo import MongoClient
con = MongoClient('localhost', port=27017)

In [270]:
durations = con.db.durations
durations

Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'db'), 'durations')

In [264]:
# TODO: Figure out TypeError in the following code
# for duration in df['duration']:
#    durations.insert_one(duration)

Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'durations')

TypeError: 'Collection' object is not callable. If you meant to call the 'insert_one' method on a 'Database' object it is failing because no such method exists.